INSERT INTO DEF_FUNC(OID, DISCRIMINATOR, CODE, LEVEL, PARENT, SYSTYPE, SEQUENCE, NAME, PATH, DESC, STATUS, UPDATER, UPDATETIME) values ('41', 'P', 919920, '2', 919910, 'A', 710, 'LINE 聯絡人', 'line/contacts', '','1', 'system', current timestamp);
INSERT INTO DEF_ROLEFUNC(OID, FUNCCODE,ROLECODE, UPDATER, UPDATETIME) values ('919920', 919920,'AI0001', 'system', current timestamp);
